(function(g){var window=this;var Vva=function(a,b){return g.Mb(a,b)},Y5=function(a,b,c){a.w.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.G)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.fn(a.w,b,c)},Wva=function(a,b){var c=[];
g.mk(b,function(d){try{var e=g.io.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.ho(e)&&c.push(d)},a);
return c},Xva=function(a,b){var c=Wva(a,b);
(0,g.y)(c,function(d){g.io.prototype.remove.call(this,d)},a)},Yva=function(a){if(a.Tc){if(a.Tc.locationOverrideToken)return{locationOverrideToken:a.Tc.locationOverrideToken};
if(null!=a.Tc.latitudeE7&&null!=a.Tc.longitudeE7)return{latitudeE7:a.Tc.latitudeE7,longitudeE7:a.Tc.longitudeE7}}return null},Zva=function(a,b){g.cb(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},$va=function(a,b){var c=b instanceof g.wc?b:g.Ac(b,/^data:image\//i.test(b));
a.src=g.xc(c)},b6=function(){},awa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},bwa=function(a){if(a.Gd&&"function"==typeof a.Gd)return a.Gd();
if("string"===typeof a)return a.split("");if(g.Oa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ib(a)},cwa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Oa(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.te&&"function"==typeof a.te)var c=a.te();else if(a.Gd&&"function"==typeof a.Gd)c=void 0;else if(g.Oa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Jb(a);d=bwa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},dwa=function(a,b,c,d){var e=new g.Um(null,void 0);
a&&g.Vm(e,a);b&&g.Wm(e,b);c&&g.Xm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.To[a]=!0;
var c=g.Ro();c&&c.publish.apply(c,arguments);g.To[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Rm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ewa(this,a.capabilities||""),fwa(this,a.experiments||""))},ewa=function(a,b){a.capabilities.clear();
(0,g.xe)(b.split(","),g.Ta(Vva,gwa)).forEach(function(c){a.capabilities.add(c)})},fwa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},hwa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},iwa=function(a){return new e6(a)},jwa=function(a){return g.Na(a)?(0,g.Fc)(a,iwa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Na(a)?"["+(0,g.Fc)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},kwa=function(a){return(0,g.Fc)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.$a(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.$a(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Js)(),c=(0,g.Is)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},lwa=function(){var a=(0,g.Is)();
a&&Xva(a,a.o.Yf(!0))},m6=function(){var a=g.Ls("yt-remote-connected-devices")||[];
g.ub(a);return a},mwa=function(a){if(g.db(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Fc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},nwa=function(a){g.Ks("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Ls("yt-remote-device-id");a||(a=i6(),g.Ks("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.cb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.cb(a,b);g.Ms()&&g.wb(a,b);a=mwa(a);if(g.db(a))try{g.Vq("remote_sid")}catch(c){}else try{g.Tq("remote_sid",a.join(","),-1)}catch(c){}},owa=function(){return g.Ls("yt-remote-session-browser-channel")},pwa=function(){return g.Ls("yt-remote-local-screens")||[]},qwa=function(){g.Ks("yt-remote-lounge-token-expiration",!0,86400)},rwa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Fc)(pwa(),function(d){return d.loungeToken}),c=(0,g.Fc)(a,function(d){return d.loungeToken});
(0,g.yi)(c,function(d){return!g.cb(b,d)})&&qwa();
g.Ks("yt-remote-local-screens",a,31536E3)},swa=function(a,b){g.Ks("yt-remote-session-browser-channel",a);
g.Ks("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.cb(c,d)||c.push(d);nwa(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.gb(a,o6());nwa(a)},twa=function(){if(!r6){var a=g.so();
a&&(r6=new g.bo(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},uwa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},vwa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?wwa(a.shift(),function(){s6(a)}):t6()},xwa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},wwa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=vwa();
a&&a(!1,"No cast extension found")},zwa=function(){if(ywa){var a=2,b=vwa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;wwa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},Awa=function(){zwa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.A.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Bd=b;this.B=(0,g.x)(this.fF,this);this.o=!1;this.u=0;this.w=this.Fa=null;this.A=[]},v6=function(a,b,c){g.A.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Bd=b;this.u=(0,g.x)(this.gF,this);this.o=[]},w6=function(a){a.Fa=g.Xf(a.u,a.Bd);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return awa(a)},y6=function(){},z6=function(){},Bwa=function(){},Dwa=function(a){return(a=Cwa(a))?new ActiveXObject(a):new XMLHttpRequest},Cwa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.C1(this);this.u=new g.Wf;this.u.setInterval(250)},Fwa=function(a,b,c){a.Bj=1;
a.Wg=Z5(b.clone());a.Ti=c;a.C=!0;Ewa(a,null)},B6=function(a,b,c,d,e){a.Bj=1;
a.Wg=Z5(b.clone());a.Ti=null;a.C=c;e&&(a.TB=!1);Ewa(a,d)},Ewa=function(a,b){a.qk=(0,g.G)();
C6(a);a.Lh=a.Wg.clone();$5(a.Lh,"t",a.F);a.Om=0;a.Lc=a.o.lr(a.o.Em()?b:null);0<a.Yr&&(a.xp=new v6((0,g.x)(a.OC,a,a.Lc),a.Yr));a.A.ka(a.Lc,"readystatechange",a.ZN);var c=a.si?g.Sb(a.si):{};a.Ti?(a.eq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Lc.send(a.Lh,a.eq,a.Ti,c)):(a.eq="GET",a.TB&&!g.me&&(c.Connection="close"),a.Lc.send(a.Lh,a.eq,null,c));a.o.af(1)},Iwa=function(a,b,c){for(var d=!0;!a.bi&&a.Om<c.length;){var e=Gwa(a,c);
if(e==D6){4==b&&(a.mh=4,E6(15),d=!1);break}else if(e==Hwa){a.mh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.mh=1,E6(17),d=!1);a.cf=a.cf&&d;d||(G6(a),H6(a))},Gwa=function(a,b){var c=a.Om,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return Hwa;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Om=d+c;return e},Kwa=function(a,b){a.qk=(0,g.G)();
C6(a);var c=b?window.location.hostname:"";a.Lh=a.Wg.clone();Y5(a.Lh,"DOMAIN",c);Y5(a.Lh,"t",a.F);try{a.jf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.mh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in Jwa)k=I6[l]=Jwa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Yc(g.ac("b/12014412"),d+"</body></html>");a.jf.open();a.jf.write(g.Tc(c));a.jf.close();a.jf.parentWindow.m=(0,g.x)(a.sN,a);a.jf.parentWindow.d=(0,g.x)(a.bB,a,!0);a.jf.parentWindow.rpcClose=(0,g.x)(a.bB,a,!1);c=a.jf.createElement("DIV");a.jf.parentWindow.document.body.appendChild(c);d=g.zc(a.Lh.toString());d=g.fd(g.xc(d));d=g.Yc(g.ac("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Zc(c,d);a.o.af(1)},C6=function(a){a.Yu=(0,g.G)()+a.B;
Lwa(a,a.B)},Lwa=function(a,b){if(null!=a.Ek)throw Error("WatchDog timer not null");
a.Ek=J6((0,g.x)(a.AN,a),b)},K6=function(a){a.Ek&&(g.v.clearTimeout(a.Ek),a.Ek=null)},H6=function(a){a.o.Bx()||a.bi||a.o.ao(a)},G6=function(a){K6(a);
g.Ke(a.xp);a.xp=null;a.u.stop();g.Tqa(a.A);if(a.Lc){var b=a.Lc;a.Lc=null;b.abort();b.dispose()}a.jf&&(a.jf=null)},F6=function(a,b){try{a.o.TA(a,b),a.o.af(4)}catch(c){}},Nwa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Mwa(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Nwa(a,b,c,d,f)},f)})}},Mwa=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
$va(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Owa=function(a){this.o=a;
this.u=new y6},Pwa=function(a){var b=M6(a.o,a.Rk,"/mail/images/cleardot.gif");
Z5(b);Nwa(b.toString(),5E3,(0,g.x)(a.YD,a),3,2E3);a.af(1)},O6=function(a){var b=a.o.I;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Ud=new A6(a,void 0,void 0,void 0),a.Ud.si=a.Wr,b=a.o,b=M6(b,b.Em()?a.xl:null,a.Xr),E6(5),!g.ke||g.Od(10))$5(b,"TYPE","xmlhttp"),B6(a.Ud,b,!1,a.xl,!1);else{$5(b,"TYPE","html");var c=a.Ud;a=!!a.xl;c.Bj=3;c.Wg=Z5(b.clone());Kwa(c,a)}},P6=function(a){g.kf.call(this);
this.headers=new g.Rm;this.U=a||null;this.w=!1;this.R=this.o=null;this.ha=this.I="";this.C=0;this.A="";this.B=this.Z=this.G=this.V=!1;this.F=0;this.P=null;this.da="";this.L=this.aa=!1},Qwa=function(a){return g.ke&&g.Nd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Rwa=function(a){return"content-type"==a.toLowerCase()},Twa=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;Swa(a);Q6(a)},Swa=function(a){a.V||(a.V=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Vwa=function(a){if(a.w&&"undefined"!=typeof g.H1)if(a.R[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.Xf(a.PA,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.qd(1,String(a.I));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Uwa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";Swa(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){Wwa(a);
var c=a.o,d=a.R[0]?g.Ka:null;a.o=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Wwa=function(a){a.o&&a.L&&(a.o.ontimeout=null);
a.P&&(g.v.clearTimeout(a.P),a.P=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.ha+" "+a.I+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.I=null!=b?b:null;this.C=c||!1},Xwa=function(a,b){this.o=a;
this.map=b;this.context=null},Ywa=function(a){g.Me.call(this,"statevent",a)},Zwa=function(a,b){g.Me.call(this,"timingevent",a);
this.size=b},$wa=function(a){g.Me.call(this,"serverreachability",a)},cxa=function(a){axa(a);
if(3==a.o){var b=a.hm++,c=a.Nn.clone();Y5(c,"SID",a.w);Y5(c,"RID",b);Y5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.Bj=2;b.Wg=Z5(c.clone());$va(new Image,b.Wg.toString());b.qk=(0,g.G)();C6(b)}bxa(a)},dxa=function(a){a.xE(1,0);
a.Nn=M6(a,null,a.Vr);W6(a)},axa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.hc&&(a.hc.cancel(),a.hc=null);a.ag&&(g.v.clearTimeout(a.ag),a.ag=null);X6(a);a.Od&&(a.Od.cancel(),a.Od=null);a.fh&&(g.v.clearTimeout(a.fh),a.fh=null)},exa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Xwa(a.HJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.Od||a.fh||(a.fh=J6((0,g.x)(a.aB,a),0),a.tj=0)},gxa=function(a,b){if(1==a.o){if(!b){a.hm=Math.floor(1E5*Math.random());
var c=a.hm++,d=new A6(a,"",c,void 0);d.si=null;var e=Y6(a),f=a.Nn.clone();Y5(f,"RID",c);Y5(f,"CVER","1");V6(a,f);Fwa(d,f,e);a.Od=d;a.o=2}}else 3==a.o&&(b?fxa(a,b):0==a.u.length||a.Od||fxa(a))},fxa=function(a,b){if(b)if(6<a.ci){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.hm-1;var d=Y6(a)}else c=b.G,d=b.Ti;else c=a.hm++,d=Y6(a);var e=a.Nn.clone();Y5(e,"SID",a.w);Y5(e,"RID",c);Y5(e,"AID",a.Oj);V6(a,e);c=new A6(a,a.w,c,a.tj+1);c.si=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Od=c;Fwa(c,e,d)},V6=function(a,b){if(a.xd){var c=a.xd.Yw();
c&&g.Cb(c,function(d,e){Y5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.ci&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.ci?e:f-d;try{g.Cb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},hxa=function(a){a.hc||a.ag||(a.F=1,a.ag=J6((0,g.x)(a.ZA,a),0),a.lj=0)},Z6=function(a){if(a.hc||a.ag||3<=a.lj)return!1;
a.F++;a.ag=J6((0,g.x)(a.ZA,a),ixa(a,a.lj));a.lj++;return!0},N6=function(a,b,c){a.bq=c;
a.xf=b.qg;a.C||dxa(a)},X6=function(a){null!=a.ii&&(g.v.clearTimeout(a.ii),a.ii=null)},ixa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.xd&&(c=null);var d=(0,g.x)(a.KO,a);c||(c=new g.Um("//www.google.com/images/cleardot.gif"),Z5(c));Mwa(c.toString(),1E4,d)}else E6(2);jxa(a,b)},jxa=function(a,b){a.o=0;
a.xd&&a.xd.pw(b);bxa(a);axa(a)},bxa=function(a){a.o=0;
a.xf=-1;if(a.xd)if(0==a.A.length&&0==a.u.length)a.xd.ar();else{g.kb(a.A);var b=g.kb(a.u);a.A.length=0;a.u.length=0;a.xd.ar(b)}},M6=function(a,b,c){var d=g.bn(c);
if(""!=d.o)b&&g.Wm(d,b+"."+d.o),g.Xm(d,d.A);else{var e=window.location;d=dwa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.kl&&g.Cb(a.kl,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.ci);V6(a,d);return d},J6=function(a,b){if(!g.Pa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new Ywa(a7,a))},kxa=function(){},lxa=function(){this.o=[];
this.u=[]},mxa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.H(this.iN,0,this);g.C(this,this.o);this.Bd=5E3;this.u=0;if(g.Pa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Pa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.P=a;
this.C=b;this.w=new g.ao;this.u=new b7(this.nO,this);this.o=null;this.tb=!1;this.B=null;this.I="";this.G=this.A=0;this.F=[];this.L=c||!1},nxa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.bq,sessionId:a.o.w,arrayId:a.o.Oj}},oxa=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&gxa(a.o),cxa(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},pxa=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.qd(4,a))||"";b&&(this.port=":"+b);this.domain=g.rd(a)||"";a=g.Lc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.sc(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Bd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ta(a.A,d,!0),onError:g.Ta(a.w,e),Td:g.Ta(a.B,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Lq(b,a)},txa=function(){var a=qxa;
rxa();h7.push(a);sxa(h7)},i7=function(a,b){rxa();
var c=h7,d=uxa(a,String(b));g.db(c)?vxa(d):(sxa(c),(0,g.y)(c,function(e){e(d)}))},rxa=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",h7,void 0))},vxa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},sxa=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},uxa=function(a,b){var c=((0,g.G)()-wxa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.O.call(this);
this.F=a;this.o=[]},xxa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},yxa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.xe)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=xxa(a,b[d])||c;return c},zxa=function(a,b){var c=a.o.length;
a.o=(0,g.xe)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.O.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Fa=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},Axa=function(a){if(a.o.length){var b=(0,g.Fc)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.qF,a),(0,g.x)(a.pF,a))}},o7=function(a){var b=jwa(pwa());
b=(0,g.xe)(b,function(c){return!c.uuid});
return yxa(a,b)},q7=function(a,b){rwa((0,g.Fc)(a.o,hwa));
b&&qwa()},s7=function(a,b){g.O.call(this);
this.C=b;var c=g.Ls("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.cb(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Ok(this.o))},Bxa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Jb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Ok(a.o)),a.o=b,a.S("screenChange"));Cxa(a)},u7=function(a){isNaN(a.w)||g.Qo(a.w);
a.w=g.Oo((0,g.x)(a.ou,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Dxa=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Tb("Requesting availability of screen w/o lounge token.")});
return b},Cxa=function(a){a=g.Jb(g.Db(a.o,function(b){return b}));
g.ub(a);a.length?g.Ks("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};Exa(this)},Gxa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.he();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);Bxa(a.u,l,function(m){e(m?l:null)})}else c?Fxa(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Bxa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},Hxa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},Fxa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Lq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Ixa=function(a){a.o=a.w.he();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},Exa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.zF,a));Ixa(a);a.A=jwa(g.Ls("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.he,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ks("yt-remote-automatic-screen-cache",(0,g.Fc)(a.A,hwa)));x7(a);a.B[b.uuid]=b.id;g.Ks("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Ls("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.O.call(this);
this.R=c;this.I=a;this.u=b;this.w=null},z7=function(a,b){i7(a.R,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.uP,this);this.B=(0,g.x)(this.IN,this);this.A=g.Oo((0,g.x)(function(){Jxa(this,null)},this),12E4)},Kxa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ok(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Ok(b))},Jxa=function(a,b){g.Qo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.mp,a),d=(0,g.x)(a.ke,a);a.tx(b,c,d,5)}}else a.ke(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.P="";this.U=c;this.B=null;this.F=g.Ka;this.C=NaN;this.L=(0,g.x)(this.xP,this);this.o=g.Ka},Lxa=function(a){a.o=a.I.UC(a.P,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ka;
this.mp(b)},a),(0,g.x)(function(b){this.o=g.Ka;
this.ke(b)},a))},Mxa=function(a){var b={};
b.pairingCode=a.P;b.theme=a.U;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}twa()&&(b.env_useStageMdx=1);return g.zd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Oo((0,g.x)(this.Pj,this,null),150)},D7=function(a,b,c,d){g.O.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.tM,this)},Nxa=function(a,b){return b?g.$a(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},qxa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.Ke(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.YA,a,b)),b.w?a.S("yt-remote-cast2-session-change",b.w):c&&a.o.Pj(null)):a.S("yt-remote-cast2-session-change",null))},Oxa=function(a){var b=a.u.TC(),c=a.o&&a.o.u;
a=(0,g.Fc)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Nxa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Uxa=function(a,b,c,d,e,f,k){Pxa()?Qxa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Rxa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Rxa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Sxa(),c(!1))},d?g.$o("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Awa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(zwa(),s6(Txa.map(xwa))))):H7("Cannot initialize because not running Chrome")},Sxa=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);Vxa(!1);g.Wo(M7);M7.length=0},N7=function(){return!!g.Ls("yt-remote-cast-installed")},Wxa=function(){var a=g.Ls("yt-remote-cast-receiver");
return a?a.friendlyName:null},Xxa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},Yxa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Vo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Pxa=function(){var a=0<=g.Lc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Gt||a},Zxa=function(a,b){L7().init(a,b)},Qxa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ks("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Ks("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Ks("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},Rxa=function(a,b){K7(!0);
I7(!1);Zxa(a,function(c){c?(Vxa(!0),g.Xo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),Sxa());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Ks("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Vxa=function(a){H7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.P=!1;this.I=this.G=this.u=this.B=0;this.A=NaN;this.w=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.P=!1;a.hasNext=!1;a.F=0;a.C=(0,g.G)();a.B=0;a.u=0;a.G=0;a.I=0;a.A=NaN;a.w=!1},T7=function(a){return a.ab()?((0,g.G)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.G)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.G)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Tb(a.o);b.hasPrevious=a.P;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.O.call(this);
this.o=0;this.A=a;this.C=[];this.B=new lxa;this.w=this.u=null;this.I=(0,g.x)(this.pK,this);this.F=(0,g.x)(this.jm,this);this.G=(0,g.x)(this.oK,this);this.P=(0,g.x)(this.AK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.bv,this),$xa(this))):c=3;0!=c&&(b?this.bv(c):g.Oo((0,g.x)(function(){this.bv(c)},this),0));
var d=Yxa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.P)},$7=function(a){return new R7(a.A.getPlayerContextData())},$xa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Ta(this.qM,b),this))},a)},aya=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){aya(a);
a.A.setPlayerContextData(X7(b));$xa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.I),a.w.removeMediaListener(a.F),a.jm(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.I),a.w.addMediaListener(a.F),a.w.media.length&&a.jm(a.w.media[0]))},bya=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Tb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Tb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.O.call(this);
this.B=NaN;this.L=!1;this.G=this.F=this.I=this.P=NaN;this.R=[];this.A=this.C=this.w=this.Ta=this.o=null;this.V=a;this.R.push(g.Lp(window,"beforeunload",(0,g.x)(this.iF,this)));this.u=[];this.Ta=new R7;this.U=b.id;this.o=cya(this,c);this.o.subscribe("handlerOpened",this.tK,this);this.o.subscribe("handlerClosed",this.qK,this);this.o.subscribe("handlerError",this.rK,this);this.o.subscribe("handlerMessage",this.sK,this);pxa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ta.videoId;
g.Ms()&&g.Ks("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},cya=function(a,b){return new c7(f7(a.V,"/bc"),b)},h8=function(a,b){a.S("proxyStateChange",b)},dya=function(a){a.B=g.Oo((0,g.x)(function(){g8("Connecting timeout");
this.rj(1)},a),2E4)},i8=function(a){g.Qo(a.B);
a.B=NaN},j8=function(a){g.Qo(a.P);
a.P=NaN},eya=function(a){k8(a);
a.I=g.Oo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Qo(a.I);
a.I=NaN},gya=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.rx()&&a.Ta.reset(),h8(a,1),l8(a,"getNowPlaying"),fya(a)):a.rj(1)},hya=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ta.videoId&&(g.Pb(b.params)?a.Ta.o=null:a.Ta.o=b.params,a.S("remotePlayerChange"))},iya=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ta.listId=b.params.listId||a.Ta.listId;W7(a.Ta,c,d);a.S("remoteQueueChange")},kya=function(a,b){b.params=b.params||{};
iya(a,b);jya(a,b);a.S("autoplayDismissed")},jya=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Ta,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ta.playerState&&(c=-1E3);a.Ta.playerState=c;c=Number(b.params.loadedTime);a.Ta.I=isNaN(c)?0:c;c=Number(b.params.duration);a.Ta.G=isNaN(c)?0:c;c=a.Ta;var d=Number(b.params.liveIngestionTime);c.A=d;c.w=isNaN(d)?!1:!0;c=a.Ta;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Ta.playerState?eya(a):k8(a);a.S("remotePlayerChange")},lya=function(a,b){if(-1E3!=
a.Ta.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ta.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Ta,isNaN(c)?0:c);a.S("remotePlayerChange")}},mya=function(a,b){var c="true"==b.params.muted;
a.Ta.volume=parseInt(b.params.volume,10);a.Ta.muted=c;a.S("remotePlayerChange")},nya=function(a,b){a.C=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},oya=function(a,b){var c="true"==b.params.hasNext;
a.Ta.P="true"==b.params.hasPrevious;a.Ta.hasNext=c;a.S("previousNextChange")},fya=function(a){g.Qo(a.G);
a.G=g.Oo((0,g.x)(a.rj,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Ok(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Ad=a;this.u=[];this.u.push(this.Ad.$_s("screenChange",(0,g.x)(this.sP,this)));this.u.push(this.Ad.$_s("onlineScreenChange",(0,g.x)(this.RL,this)))},tya=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.L("MDX_CONFIG")||b;lwa();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),twa()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",o8,void 0));pya();var c=p8();if(!c){var d=new v7(n8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Uxa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Ok(b)),s8.push(g.Vo("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.Vo("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Vo("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Vo("yt-remote-cast2-session-change",qya)),s8.push(g.Vo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),Xxa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.Eo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Ok(a)),rya(a),c.start(),q8()||sya())},vya=function(){var a=uya();
N7()&&g.Ls("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},uya=function(){var a=p8().Ad.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return kwa(a)},y8=function(){var a=wya();
!a&&N7()&&Wxa()&&(a={key:"cast-selector-receiver",name:Wxa()});return a},wya=function(){var a=uya(),b=w8();
b||(b=u8());return g.$a(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().he();return k6(b,a)},qya=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},xya=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},yya=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||xya("");g.Ia("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.Ms();
if(!a)return null;var b=p8().he();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{xya(a.id);var c=new f8(n8,a,v8());c.connect(b,yya());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},sya=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),Xxa(),r8("Skipping connecting because no session screen found."))},pya=function(){var a=v8();
if(g.Pb(a)){a=o6();var b=g.Ls("yt-remote-session-name")||"",c=g.Ls("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},rya=function(a){a?(g.Ks("yt-remote-session-app",a.app),g.Ks("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.A.call(this);
this.B=a;this.u=b;this.w=new g.Nr(this);g.C(this,this.w);this.w.K(b,"onCaptionsTrackListChanged",this.nL);this.w.K(b,"captionschanged",this.nK);this.w.K(b,"captionssettingschanged",this.hC);this.w.K(b,"videoplayerreset",this.np);this.w.K(b,"mdxautoplaycancel",this.XD);this.U=this.w.K(b,"onVolumeChange",this.wA);this.G=!1;this.o=c;c.ea();c.subscribe("proxyStateChange",this.SA,this);c.subscribe("remotePlayerChange",this.om,this);c.subscribe("remoteQueueChange",this.np,this);c.subscribe("autoplayUpNext",
this.gA,this);c.subscribe("previousNextChange",this.NA,this);c.subscribe("nowAutoplaying",this.IA,this);c.subscribe("autoplayDismissed",this.fA,this);this.suggestion=null;this.I=new g.LC(64);this.A=new g.H(this.fC,500,this);g.C(this,this.A);this.C=new g.H(this.gC,1E3,this);g.C(this,this.C);this.L=new u6(this.TO,0,this);g.C(this,this.L);this.F={};this.R=new g.H(this.GC,1E3,this);g.C(this,this.R);this.P=new v6(this.tI,1E3,this);g.C(this,this.P);this.V=g.Ka;this.hC();this.np();this.om()},H8=function(a,
b){var c=a.B,d=a.u.getVideoData().lengthSeconds;
c.R=b||0;c.player.S("progresssync",b,d)},zya=function(a){H8(a,0);
a.A.stop();I8(a,new g.LC(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.Vb(c,b));a.o.YB(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.zf,Yva(c));I8(a,new g.LC(1))},Aya=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{Qx:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.I;if(!g.RC(c,b)){var d=g.V(b,2);d!=g.V(a.I,2)&&g.XS(a.u.app,d);a.I=b;Bya(a.B,c,b)}},M8=function(a){g.R.call(this,{D:"div",
H:"ytp-remote",J:[{D:"div",H:"ytp-remote-display-status",J:[{D:"div",H:"ytp-remote-display-status-icon",J:[g.ZM()]},{D:"div",H:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.LN(this,250);g.C(this,this.u);this.w=a;this.K(a,"presentingplayerstatechange",this.A);Cya(this,g.QK(a))},Cya=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.GM("Erro em $RECEIVER_NAME",c):b.ab()||g.V(b,4)?g.GM("Reproduzindo em $RECEIVER_NAME",c):g.GM("Conectado a $RECEIVER_NAME",c);a.la("statustext",c);a.u.show()}else a.u.hide()},N8=function(a,b){g.IO.call(this,"Reproduzir em",0,a,b);
this.A=a;this.G={};this.K(a,"onMdxReceiversChange",this.L);this.K(a,"presentingplayerstatechange",this.L);this.L()},O8=function(){g.R.call(this,{D:"div",
H:"ytp-mdx-popup-dialog",O:{role:"dialog"},J:[{D:"div",H:"ytp-mdx-popup-dialog-inner-content",J:[{D:"div",H:"ytp-mdx-popup-title",W:"Voc\u00ea n\u00e3o fez login"},{D:"div",H:"ytp-mdx-popup-description",W:"Os v\u00eddeos que voc\u00ea assistir poder\u00e3o ser adicionados ao hist\u00f3rico de visualiza\u00e7\u00e3o da TV e influenciar\u00e3o as recomenda\u00e7\u00f5es dela. Para evitar isso, cancele e fa\u00e7a login no YouTube em um computador."},{D:"div",H:"ytp-mdx-privacy-popup-buttons",J:[{D:"button",
Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancelar"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],W:"Confirmar"}]}]}]});this.u=new g.LN(this,250);this.cancelButton=this.o["ytp-mdx-privacy-popup-cancel"];this.confirmButton=this.o["ytp-mdx-privacy-popup-confirm"];g.C(this,this.u);this.K(this.cancelButton,"click",this.w);this.K(this.confirmButton,"click",this.A)},P8=function(a){g.wL.call(this,a);
this.u={key:i6(),name:"Este computador"};this.B=null;this.A=[];this.U=this.o=null;this.P=[this.u];this.w=this.u;this.F=new g.LC(64);this.R=0;this.I=-1;this.C=null;if(!g.dz(this.player.M())){a=this.player;var b=g.fC(a);b&&(b=b.Yl())&&(b=new N8(a,b),g.C(this,b));b=new M8(a);g.C(this,b);g.jL(a,b.element,4);this.C=new O8;g.C(this,this.C);g.jL(a,this.C.element,4);this.L=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},Bya=function(a,b,
c){a.F=c;
a.player.S("presentingplayerstatechange",new g.cH(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.P(a.player.M().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.L||!a.C);if(c?0:g.mz(a.player.M())||"WEB_EMBEDDED_PLAYER"==a.player.M().deviceParams.c)g.QK(a.player).ab()?a.player.pauseVideo():(a.G=(0,g.x)(a.NN,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.Zb(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=
c.videoId;if(!d&&!e||(2==a.player.getAppState()||1==a.player.getAppState())&&g.P(a.player.M().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.va(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.zf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=Yva(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.Ok(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().he(),(c=k6(c,b.key))&&A8(c,1))}},Jwa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},Dya={},gwa={VP:"atp",DS:"ska",rS:"que",LR:"mus",CS:"sus",XQ:"dsp",zS:"seq"},r6,n6="",ywa=uwa("loadCastFramework")||uwa("loadCastApplicationFramework"),Txa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Va(u6,g.A);g.h=u6.prototype;g.h.eF=function(a){this.A=arguments;this.o=!1;this.Fa?this.w=(0,g.G)()+this.Bd:this.Fa=g.Xf(this.B,this.Bd)};
g.h.stop=function(){this.Fa&&(g.v.clearTimeout(this.Fa),this.Fa=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Fb.X.call(this)};
g.h.fF=function(){this.w?(this.Fa=g.Xf(this.B,this.w-(0,g.G)()),this.w=null):(this.Fa=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Va(v6,g.A);g.h=v6.prototype;g.h.Aj=!1;g.h.wl=0;g.h.Fa=null;g.h.Ax=function(a){this.o=arguments;this.Fa||this.wl?this.Aj=!0:w6(this)};
g.h.stop=function(){this.Fa&&(g.v.clearTimeout(this.Fa),this.Fa=null,this.Aj=!1,this.o=[])};
g.h.pause=function(){this.wl++};
g.h.resume=function(){this.wl--;this.wl||!this.Aj||this.Fa||(this.Aj=!1,w6(this))};
g.h.X=function(){v6.Fb.X.call(this);this.stop()};
g.h.gF=function(){this.Fa=null;this.Aj&&!this.wl&&(this.Aj=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Cwa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Va(Bwa,z6);S8=new Bwa;g.h=A6.prototype;g.h.si=null;g.h.cf=!1;g.h.Ek=null;g.h.Yu=null;g.h.qk=null;g.h.Bj=null;g.h.Wg=null;g.h.Lh=null;g.h.Ti=null;g.h.Lc=null;g.h.Om=0;g.h.jf=null;g.h.eq=null;g.h.mh=null;g.h.yl=-1;g.h.TB=!0;g.h.bi=!1;g.h.Yr=0;g.h.xp=null;var Hwa={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.ZN=function(a){a=a.target;var b=this.xp;b&&3==R6(a)?b.Ax():this.OC(a)};
g.h.OC=function(a){try{if(a==this.Lc)a:{var b=R6(this.Lc),c=this.Lc.C,d=this.Lc.getStatus();if(g.ke&&!g.Od(10)||g.me&&!g.Nd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ah&&!T6(this.Lc))break a;this.bi||4!=b||7==c||(8==c||0>=d?this.o.af(3):this.o.af(2));K6(this);var e=this.Lc.getStatus();this.yl=e;var f=T6(this.Lc);(this.cf=200==e)?(4==b&&G6(this),this.C?(Iwa(this,b,f),g.Ah&&this.cf&&3==b&&(this.A.ka(this.u,"tick",this.RN),this.u.start())):F6(this,f),this.cf&&!this.bi&&(4==b?this.o.ao(this):(this.cf=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mh=3,E6(13)):(this.mh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Lc&&T6(this.Lc)}finally{}};
g.h.RN=function(){var a=R6(this.Lc),b=T6(this.Lc);this.Om<b.length&&(K6(this),Iwa(this,a,b),this.cf&&4!=a&&C6(this))};
g.h.sN=function(a){J6((0,g.x)(this.rN,this,a),0)};
g.h.rN=function(a){this.bi||(K6(this),F6(this,a),C6(this))};
g.h.bB=function(a){J6((0,g.x)(this.qN,this,a),0)};
g.h.qN=function(a){this.bi||(G6(this),this.cf=a,this.o.ao(this),this.o.af(4))};
g.h.cancel=function(){this.bi=!0;G6(this)};
g.h.AN=function(){this.Ek=null;var a=(0,g.G)();0<=a-this.Yu?(2!=this.Bj&&this.o.af(3),G6(this),this.mh=2,E6(18),H6(this)):Lwa(this,this.Yu-a)};
g.h.getLastError=function(){return this.mh};g.h=Owa.prototype;g.h.Wr=null;g.h.Ud=null;g.h.yp=!1;g.h.Cx=null;g.h.Kn=null;g.h.Is=null;g.h.Xr=null;g.h.ye=null;g.h.qg=-1;g.h.xl=null;g.h.Rk=null;g.h.connect=function(a){this.Xr=a;a=M6(this.o,null,this.Xr);E6(3);this.Cx=(0,g.G)();var b=this.o.G;null!=b?(this.xl=b[0],(this.Rk=b[1])?(this.ye=1,Pwa(this)):(this.ye=2,O6(this))):($5(a,"MODE","init"),this.Ud=new A6(this,void 0,void 0,void 0),this.Ud.si=this.Wr,B6(this.Ud,a,!1,null,!0),this.ye=0)};
g.h.YD=function(a){if(a)this.ye=2,O6(this);else{E6(4);var b=this.o;b.xf=b.ah.qg;$6(b,9)}a&&this.af(2)};
g.h.lr=function(a){return this.o.lr(a)};
g.h.abort=function(){this.Ud&&(this.Ud.cancel(),this.Ud=null);this.qg=-1};
g.h.Bx=function(){return!1};
g.h.TA=function(a,b){this.qg=a.yl;if(0==this.ye)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.xf=this.qg;$6(c,2);return}this.xl=c[0];this.Rk=c[1]}else c=this.o,c.xf=this.qg,$6(c,2);else if(2==this.ye)if(this.yp)E6(7),this.Is=(0,g.G)();else if("11111"==b){if(E6(6),this.yp=!0,this.Kn=(0,g.G)(),c=this.Kn-this.Cx,!g.ke||g.Od(10)||500>c)this.qg=200,this.Ud.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Kn=this.Is=(0,g.G)(),this.yp=!1};
g.h.ao=function(){this.qg=this.Ud.yl;if(this.Ud.cf)0==this.ye?this.Rk?(this.ye=1,Pwa(this)):(this.ye=2,O6(this)):2==this.ye&&((!g.ke||g.Od(10)?!this.yp:200>this.Is-this.Kn)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.ye?E6(9):2==this.ye&&E6(10);var a=this.o;this.Ud.getLastError();a.xf=this.qg;$6(a,2)}};
g.h.Em=function(){return this.o.Em()};
g.h.isActive=function(){return this.o.isActive()};
g.h.af=function(a){this.o.af(a)};g.Va(P6,g.kf);var Uwa=/^https?$/i,Eya=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.A="";this.C=0;this.ha=b;this.V=!1;this.w=!0;this.o=this.U?Dwa(this.U):Dwa(S8);this.R=this.U?this.U.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.PA,this);try{b6(S6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));Twa(this,f);return}a=c||
"";var e=this.headers.clone();d&&cwa(d,function(f,k){e.set(k,f)});
d=g.$a(e.te(),Rwa);c=g.v.FormData&&a instanceof g.v.FormData;!g.cb(Eya,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.da&&(this.o.responseType=this.da);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{Wwa(this),0<this.F&&(this.L=Qwa(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.L)),this.L?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.Dx,this)):this.P=g.Xf(this.Dx,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),Twa(this,f)}};
g.h.Dx=function(){"undefined"!=typeof g.H1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Fb.X.call(this)};
g.h.PA=function(){this.ea()||(this.Z||this.G||this.B?Vwa(this):this.sM())};
g.h.sM=function(){Vwa(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.kl=null;g.h.Od=null;g.h.hc=null;g.h.Vr=null;g.h.Nn=null;g.h.cw=null;g.h.Zn=null;g.h.hm=0;g.h.HJ=0;g.h.xd=null;g.h.fh=null;g.h.ag=null;g.h.ii=null;g.h.ah=null;g.h.bq=null;g.h.Oj=-1;g.h.jy=-1;g.h.xf=-1;g.h.tj=0;g.h.lj=0;g.h.ci=8;var a7=new g.kf;g.Va(Ywa,g.Me);g.Va(Zwa,g.Me);g.Va($wa,g.Me);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Vr=b;this.kl=c||{};d&&void 0!==e&&(this.kl.OSID=d,this.kl.OAID=e);this.C?(J6((0,g.x)(this.xw,this,a),100),dxa(this)):this.xw(a)};
g.h.xw=function(a){this.ah=new Owa(this);this.ah.Wr=null;this.ah.u=this.B;this.ah.connect(a)};
g.h.Bx=function(){return 0==this.o};
g.h.aB=function(a){this.fh=null;gxa(this,a)};
g.h.ZA=function(){this.ag=null;this.hc=new A6(this,this.w,"rpc",this.F);this.hc.si=null;this.hc.Yr=0;var a=this.cw.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.w);Y5(a,"CI",this.bq?"0":"1");Y5(a,"AID",this.Oj);V6(this,a);if(!g.ke||g.Od(10))Y5(a,"TYPE","xmlhttp"),B6(this.hc,a,!0,this.Zn,!1);else{Y5(a,"TYPE","html");var b=this.hc,c=!!this.Zn;b.Bj=3;b.Wg=Z5(a.clone());Kwa(b,c)}};
g.h.TA=function(a,b){if(0!=this.o&&(this.hc==a||this.Od==a))if(this.xf=a.yl,this.Od==a&&3==this.o)if(7<this.ci){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.ag){if(this.hc)if(this.hc.qk+3E3<this.Od.qk)X6(this),this.hc.cancel(),this.hc=null;else break a;Z6(this);E6(19)}}else this.jy=c[1],0<this.jy-this.Oj&&37500>c[2]&&this.bq&&0==this.lj&&!this.ii&&(this.ii=J6((0,g.x)(this.jK,this),6E3));else $6(this,11)}else b!=Dya.sQ.o&&$6(this,11);else if(this.hc==
a&&X6(this),!g.hc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Oj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.Zn=e[2],e=e[3],null!=e?this.ci=e:this.ci=6,this.o=3,this.xd&&this.xd.rw(),this.cw=M6(this,this.Em()?this.Zn:null,this.Vr),hxa(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.xd&&this.xd.qw(e),this.lj=0)}}};
g.h.jK=function(){null!=this.ii&&(this.ii=null,this.hc.cancel(),this.hc=null,Z6(this),E6(20))};
g.h.ao=function(a){if(this.hc==a){X6(this);this.hc=null;var b=2}else if(this.Od==a)this.Od=null,b=1;else return;this.xf=a.yl;if(0!=this.o)if(a.cf)1==b?(b=(0,g.G)()-a.qk,a7.dispatchEvent(new Zwa(a7,a.Ti?a.Ti.length:0,b,this.tj)),W6(this),this.A.length=0):hxa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.xf)){if(d=1==b)this.Od||this.fh||1==this.o||2<=this.tj?d=!1:(this.fh=J6((0,g.x)(this.aB,this,a),ixa(this,this.tj)),this.tj++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.xE=function(a){if(!g.cb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.KO=function(a){a?E6(2):(E6(1),jxa(this,8))};
g.h.lr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.aa=!1;return a};
g.h.isActive=function(){return!!this.xd&&this.xd.isActive(this)};
g.h.af=function(a){a7.dispatchEvent(new $wa(a7,a))};
g.h.Em=function(){return!(!g.ke||g.Od(10))};
g.h=kxa.prototype;g.h.rw=function(){};
g.h.qw=function(){};
g.h.pw=function(){};
g.h.ar=function(){};
g.h.Yw=function(){return{}};
g.h.isActive=function(){return!0};g.h=lxa.prototype;g.h.isEmpty=function(){return g.db(this.o)&&g.db(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.cb(this.o,a)||g.cb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Yqa)(b,a);0<=c?(g.fb(b,c),b=!0):b=!1;return b||g.gb(this.u,a)};
g.h.Gd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Va(b7,g.A);g.h=b7.prototype;g.h.iN=function(){this.Bd=Math.min(3E5,2*this.Bd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Bd+15E3*Math.random();g.An(this.o,a);this.u=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Bd=5E3};g.Va(c7,kxa);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.Dh=function(a){return this.w.ti(a)};
g.h.S=function(a,b){return this.w.S.apply(this.w,arguments)};
g.h.dispose=function(){this.tb||(this.tb=!0,g.Ke(this.w),oxa(this),g.Ke(this.u),this.u=null)};
g.h.ea=function(){return this.tb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.I="";this.u.stop();this.B=a||null;this.A=b||0;a=this.P+"/test";b=this.P+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.xd=null);d.xd=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Oj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Vb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&exa(this.o,c)};
g.h.rw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)exa(this.o,a[b])}this.S("handlerOpened")};
g.h.pw=function(a){var b=2==a&&401==this.o.xf;4==a||b||this.u.start();this.S("handlerError",a)};
g.h.ar=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Yw=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.Vb(a,this.B);return a};
g.h.qw=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),cxa(this.o)):this.S("handlerMessage",new mxa(a[0],a[1]))};
g.h.nO=function(){this.u.isActive();var a=this.o,b=0;a.hc&&b++;a.Od&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var wxa=(0,g.G)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Va(m7,g.O);m7.prototype.he=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.O);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Fa)&&this.SC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Fa)||(g.Qo(this.Fa),this.Fa=NaN)};
g.h.X=function(){this.stop();g.O.prototype.X.call(this)};
g.h.SC=function(){this.Fa=NaN;this.o=g.Lq(f7(this.C,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.qP,this),onError:(0,g.x)(this.pP,this),Td:(0,g.x)(this.rP,this)})};
g.h.qP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.S("pairingComplete",new e6(c))};
g.h.pP=function(a){this.o=null;a.status&&404==a.status?this.u>=Fya.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=Fya[this.u],this.Fa=g.Oo((0,g.x)(this.SC,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.h.rP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var Fya=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Va(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.S("screenChange");!g.Ls("yt-remote-lounge-token-expiration")&&Axa(this);g.Qo(this.u);this.u=g.Oo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);xxa(this,a);q7(this,!1);this.S("screenChange");b(a);a.token||Axa(this)};
g.h.remove=function(a,b){var c=o7(this);zxa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.h.Yp=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.h.X=function(){g.Qo(this.u);p7.Fb.X.call(this)};
g.h.qF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.pF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.O);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Ls("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?u7(this):(this.A=(0,g.G)()+3E5,g.Ks("yt-remote-fast-check-period",this.A),this.ou())};
g.h.isEmpty=function(){return g.Pb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Db(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.Qo(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.O.prototype.X.call(this)};
g.h.ou=function(){g.Qo(this.w);this.w=NaN;this.u&&this.u.abort();var a=Dxa(this);if(a6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Jb(a).join(",")},(0,g.x)(this.RM,this,a),(0,g.x)(this.QM,this))}else t7(this,{}),u7(this)};
g.h.RM=function(a,b){this.u=null;var c=g.Jb(Dxa(this));if(g.vb(c,g.Jb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Tb("Changing Screen set during request."),this.ou()};
g.h.QM=function(a){this.Tb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Tb=function(a){i7("OnlineScreenService",a)};g.Va(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.S("screenChange"),this.u.isEmpty()||this.S("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.Yp=function(a,b,c,d){this.w.contains(a)?this.w.Yp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.he=function(a){return a?this.o:g.jb(this.o,(0,g.xe)(this.A,function(b){return!this.contains(b)},this))};
g.h.TC=function(){return(0,g.xe)(this.he(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.UC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ke(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ke(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.tP=function(a,b,c,d){g.Lq(f7(this.C,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||Hxa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Hxa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Td:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.Ke(this.w);g.Ke(this.u);v7.Fb.X.call(this)};
g.h.zF=function(){Ixa(this);this.S("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Va(y7,g.O);g.h=y7.prototype;g.h.mp=function(a){this.w=a;this.S("sessionScreen",this.w)};
g.h.ke=function(a){this.ea()||(a&&z7(this,""+a),this.w=null,this.S("sessionScreen",null))};
g.h.info=function(a){i7(this.R,a)};
g.h.WC=function(){return null};
g.h.yu=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.yu("");y7.Fb.X.call(this)};g.Va(A7,y7);g.h=A7.prototype;g.h.xu=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Kxa(this)};
g.h.Pj=function(a){this.info("launchWithParams no-op for Cast: "+g.Ok(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.ke()},this),(0,g.x)(function(){this.ke(Error("Failed to stop receiver app."))},this)):this.ke(Error("Stopping cast device witout session."))};
g.h.yu=g.Ka;g.h.X=function(){this.info("disposeInternal");g.Qo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Fb.X.call(this)};
g.h.IN=function(a,b){if(!this.ea())if(b){var c=x6(b);if(g.Qa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ok(c));switch(d){case "mdxSessionStatus":Jxa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.tx=function(a,b,c,d){Gxa(this.I,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Oo((0,g.x)(this.tx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.WC=function(){return this.o};
g.h.uP=function(a){this.ea()||a||(z7(this,"Cast session died."),this.ke())};g.Va(B7,y7);g.h=B7.prototype;g.h.xu=function(a){this.A=a;this.A.addUpdateListener(this.L)};
g.h.Pj=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ka;g.Qo(this.C);this.A?this.A.stop((0,g.x)(this.ke,this,null),(0,g.x)(this.ke,this,"Failed to stop DIAL device.")):this.ke()};
g.h.X=function(){this.o();this.o=g.Ka;g.Qo(this.C);this.A&&this.A.removeUpdateListener(this.L);this.A=null;B7.Fb.X.call(this)};
g.h.xP=function(a){this.ea()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ka,this.ke())};
g.h.ts=function(a){this.P=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Mxa(this));a(b);Lxa(this)}else this.F=(0,g.x)(function(){g.Qo(this.C);this.F=g.Ka;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Mxa(this));a(c);Lxa(this)},this),this.C=g.Oo((0,g.x)(function(){this.F()},this),100)};
g.h.SF=function(a,b,c){Gxa(this.I,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.mp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.ts(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.ts(b,c)},this))};g.Va(C7,y7);C7.prototype.stop=function(){this.ke()};
C7.prototype.xu=g.Ka;C7.prototype.Pj=function(){g.Qo(this.o);this.o=NaN;var a=k6(this.I.he(),this.u.label);a?this.mp(a):this.ke(Error("No such screen"))};
C7.prototype.X=function(){g.Qo(this.o);this.o=NaN;C7.Fb.X.call(this)};g.Va(D7,g.O);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.xM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.WA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.HK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.A),txa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.VC,this)),this.w=Oxa(this),chrome.cast.setCustomReceivers(this.w,g.Ka,(0,g.x)(function(k){this.Tb("Failed to set initial custom receivers: "+g.Ok(k))},this)),this.S("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Tb("Failed to initialize API: "+g.Ok(k));
b(!1)},this))};
g.h.uO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.he(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Nxa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ka,(0,g.x)(function(e){this.Tb("Failed to set initial custom receivers: "+g.Ok(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.yu(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.vO=function(a){this.ea()?this.Tb("Setting connection data on disposed cast v2"):this.o?this.o.Pj(a):this.Tb("Setting connection data without a session")};
g.h.wP=function(){this.ea()?this.Tb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.WA,this),(0,g.x)(this.VM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.VC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=qxa,b=g.w("yt.mdx.remote.debug.handlers_");g.gb(b||[],a);g.Ke(this.o);D7.Fb.X.call(this)};
g.h.Tb=function(a){i7("Controller",a)};
g.h.YA=function(a,b){this.o==a&&(b||G7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.h.tM=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.S("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Tb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Tb("Stopping receiver w/o session: "+a.friendlyName)}else this.Tb("onReceiverAction_ called without receiver.")};
g.h.HK=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Tb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Tb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Tb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.SF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.ts,b))};
g.h.WA=function(a){if(!this.ea()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Tb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.he(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ke(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.YA,this,this.o)),this.o.Pj(null));this.o.xu(a)}}};
g.h.vP=function(){return this.o?this.o.WC():null};
g.h.VM=function(a){this.ea()||(this.Tb("Failed to estabilish a session: "+g.Ok(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.xM=function(a){E7("Receiver availability updated: "+a);if(!this.ea()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.S("yt-remote-cast2-availability-change",F7(this))}};
g.h.VC=function(){this.ea()||(this.w=Oxa(this),E7("Updating custom receivers: "+g.Ok(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ka,(0,g.x)(function(){this.Tb("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.vO;D7.prototype.setConnectedScreenStatus=D7.prototype.uO;D7.prototype.stopSession=D7.prototype.wP;D7.prototype.getCastSession=D7.prototype.vP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];g.h=R7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.P=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.w=!isNaN(this.A))};
g.h.ab=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.w?this.G+T7(this):this.G};
g.h.clone=function(){return new R7(X7(this))};g.r(Z7,g.O);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ka,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ka,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ab()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.S("remotePlayerChange")}else a8(this,g.Ta(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ka,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.S("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Tb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Tb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Ta(this.setVolume,a,b))};
g.h.YB=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Ok(b.style),g.Vb(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Ta(this.YB,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Ta(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Ok(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.RC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Ta(this.RC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Ta(this.nextVideo,a,b))};
g.h.Gw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Gw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.O.prototype.dispose.call(this)};
g.h.X=function(){aya(this);this.A=null;this.B.clear();Y7(this,null);g.O.prototype.X.call(this)};
g.h.bv=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.db(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.qM=function(a,b){this.S(a,b)};
g.h.pK=function(a){if(!a)this.jm(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.jm=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),bya(this),this.S("remotePlayerChange")};
g.h.oK=function(a){a?(bya(this),this.S("remotePlayerChange")):this.jm(null)};
g.h.AK=function(){var a=Yxa();a&&Y7(this,a)};
g.h.Tb=function(a){i7("CP",a)};g.r(f8,g.O);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Ta.listId=c);this.Ta.videoId=d;this.Ta.index=k||0;this.Ta.state=3;U7(this.Ta,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Ok(l));this.o.connect({method:"setPlaylist",
params:g.Ok(l)},a,owa())}else g8("Connecting without params"),this.o.connect({},a,owa());dya(this)};
g.h.dispose=function(){this.ea()||(this.S("beforeDispose"),h8(this,3));g.O.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.Qo(this.F);this.F=NaN;g.Qo(this.G);this.G=NaN;this.w=null;g.Mp(this.R);this.R.length=0;this.o.dispose();g.O.prototype.X.call(this);this.A=this.C=this.u=this.Ta=this.o=null};
g.h.iF=function(){this.rj(2)};
g.h.tK=function(){g8("Channel opened");this.L&&(this.L=!1,j8(this),this.P=g.Oo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.rj(1)},this),15E3));
swa(nxa(this.o),this.U)};
g.h.qK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.rK=function(a){q6();isNaN(this.sl())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.L=!0,g8("Channel error: "+a+" with reconnection in "+this.sl()+" ms"),h8(this,2))};
g.h.sK=function(a){a.params?g8("Received: action="+a.action+", params="+g.Ok(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.Fc)(a,function(c){return new d6(c)});
a=!!g.$a(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
gya(this,a);break;case "loungeScreenDisconnected":g.ib(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
gya(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.$a(this.u,function(c){return b?c.id==b.id:!1})||Zva(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.ib(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":iya(this,a);break;case "nowPlaying":kya(this,a);break;case "onStateChange":jya(this,a);break;case "onAdStateChange":lya(this,a);break;case "onVolumeChanged":mya(this,a);break;case "onSubtitlesTrackChanged":hya(this,a);break;case "nowAutoplaying":nya(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.S("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.S("autoplayModeChange",this.A);"DISABLED"==this.A&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":oya(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.jO=function(){if(this.w){var a=this.w;this.w=null;this.Ta.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.XE=function(){var a=3;this.ea()||(a=0,isNaN(this.sl())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.rj=function(a){g8("Disconnecting with "+a);i8(this);this.S("beforeDisconnect",a);1==a&&q6();oxa(this.o,a);this.dispose()};
g.h.WE=function(){var a=this.Ta;this.w&&(a=this.Ta.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.wO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Ta.videoId&&(this.w=b.videoId,g.Qo(this.F),this.F=g.Oo((0,g.x)(this.jO,this),5E3));var c=[];this.Ta.listId==b.listId&&this.Ta.videoId==b.videoId&&this.Ta.index==b.index||c.push("remoteQueueChange");this.Ta.playerState==b.playerState&&this.Ta.volume==b.volume&&this.Ta.muted==b.muted&&V7(this.Ta)==V7(b)&&g.Ok(this.Ta.o)==g.Ok(b.o)||c.push("remotePlayerChange");this.Ta.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.h.rx=function(){var a=this.o.C.id,b=g.$a(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.sl=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.G)():NaN};
g.h.LE=function(){return this.A||"UNSUPPORTED"};
g.h.ME=function(){return this.C||""};
g.h.oP=function(){if(!isNaN(this.sl())){var a=this.o.u;g.Bn(a.o);a.start()}};
g.h.rO=function(a,b){l8(this,a,b);fya(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.Dh;f8.prototype.getProxyState=f8.prototype.XE;f8.prototype.disconnect=f8.prototype.rj;f8.prototype.getPlayerContextData=f8.prototype.WE;f8.prototype.setPlayerContextData=f8.prototype.wO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.rx;f8.prototype.getReconnectTimeout=f8.prototype.sl;f8.prototype.getAutoplayMode=f8.prototype.LE;f8.prototype.getAutoplayVideoId=f8.prototype.ME;f8.prototype.reconnect=f8.prototype.oP;
f8.prototype.sendMessage=f8.prototype.rO;g.r(m8,m7);g.h=m8.prototype;g.h.he=function(a){return this.Ad.$_gs(a)};
g.h.contains=function(a){return!!this.Ad.$_c(a)};
g.h.get=function(a){return this.Ad.$_g(a)};
g.h.start=function(){this.Ad.$_st()};
g.h.add=function(a,b,c){this.Ad.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Ad.$_r(a,b,c)};
g.h.Yp=function(a,b,c,d){this.Ad.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.Ad.$_ubk(this.u[a]);this.u.length=0;this.Ad=null;m7.prototype.X.call(this)};
g.h.sP=function(){this.S("screenChange")};
g.h.RL=function(){this.S("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.tP;v7.prototype.$_gsppc=v7.prototype.UC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.Yp;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.he;v7.prototype.$_gos=v7.prototype.TC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Dh;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.A);g.h=G8.prototype;
g.h.X=function(){g.A.prototype.X.call(this);this.A.stop();this.C.stop();this.L.stop();this.V();this.o.unsubscribe("proxyStateChange",this.SA,this);this.o.unsubscribe("remotePlayerChange",this.om,this);this.o.unsubscribe("remoteQueueChange",this.np,this);this.o.unsubscribe("autoplayUpNext",this.gA,this);this.o.unsubscribe("previousNextChange",this.NA,this);this.o.unsubscribe("nowAutoplaying",this.IA,this);this.o.unsubscribe("autoplayDismissed",this.fA,this);this.o=this.B=null};
g.h.nz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":$7(this.o).ab()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.P.Ax(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.nK=function(a){this.L.eF(a)};
g.h.TO=function(a){this.nz("control_subtitles_set_track",g.Pb(a)?null:a)};
g.h.hC=function(){var a=this.u.getOption("captions","track");g.Pb(a)||K8(this,a)};
g.h.wA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.om,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.om,this)}};
g.h.nL=function(){g.Pb(this.F)||Aya(this,this.F);this.G=!1};
g.h.SA=function(a,b){this.C.stop();2==b&&this.gC()};
g.h.om=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.I=1;break;case 1082:case 1083:this.B.I=0;break;default:this.B.I=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.LC(8));this.fC();break;case 1085:case 3:I8(this,new g.LC(9));break;case 1083:case 0:I8(this,new g.LC(2));this.P.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.LC(4));break;case 2:I8(this,new g.LC(4));H8(this,V7(a));
break;case -1:I8(this,new g.LC(64));break;case -1E3:I8(this,new g.LC(128,{errorCode:"mdx.remoteerror",errorMessage:"Este v\u00eddeo n\u00e3o est\u00e1 dispon\u00edvel para reprodu\u00e7\u00e3o remota."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,Aya(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.R.isActive()||this.GC()}else zya(this)};
g.h.NA=function(){this.u.S("mdxpreviousnextchange")};
g.h.np=function(){J8(this)||zya(this)};
g.h.XD=function(){this.o.Gw()};
g.h.gA=function(){};
g.h.IA=function(a){isNaN(a)||this.u.S("mdxnowautoplaying",a)};
g.h.fA=function(){this.u.S("mdxautoplaycanceled")};
g.h.tI=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.GC=function(){if(J8(this)){var a=$7(this.o);this.w.Za(this.U);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.U=this.w.K(this.u,"onVolumeChange",this.wA)}};
g.h.fC=function(){this.A.stop();if(!this.o.ea()){var a=$7(this.o);a.ab()&&I8(this,new g.LC(8));H8(this,V7(a));this.A.start()}};
g.h.gC=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.R);M8.prototype.A=function(a){Cya(this,a.state)};g.r(N8,g.IO);N8.prototype.L=function(){var a=this.A.getOption("remote","receivers");a&&1<a.length&&!this.A.getOption("remote","quickCast")?(this.G=g.xb(a,this.B,this),g.KO(this,(0,g.Fc)(a,this.B)),a=this.A.getOption("remote","currentReceiver"),this.Cb(this.B(a)),this.enable(!0)):this.enable(!1)};
N8.prototype.B=function(a){return a.key};
N8.prototype.Ye=function(a){return"cast-selector-receiver"==a?"Elenco...":this.G[a].name};
N8.prototype.hd=function(a){g.IO.prototype.hd.call(this,a);this.A.setOption("remote","currentReceiver",this.G[a]);this.u.eb()};g.r(O8,g.R);O8.prototype.Zb=function(){this.u.show()};
O8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
O8.prototype.A=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(P8,g.wL);g.h=P8.prototype;
g.h.create=function(){tya(g.Uy(this.player.M()));this.A.push(g.Vo("yt-remote-before-disconnect",this.kK,this));this.A.push(g.Vo("yt-remote-connection-change",this.yM,this));this.A.push(g.Vo("yt-remote-receiver-availability-change",this.QA,this));this.A.push(g.Vo("yt-remote-auto-connect",this.wM,this));this.A.push(g.Vo("yt-remote-receiver-resumed",this.vM,this));this.A.push(g.Vo("mdx-privacy-popup-confirm",this.VN,this));this.A.push(g.Vo("mdx-privacy-popup-cancel",this.UN,this));this.QA()};
g.h.load=function(){this.player.cancelPlayback();g.wL.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=yya())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.R=a||0,this.player.S("progresssync",a,void 0));Bya(this,this.F,this.F);g.dT(this.player.app,6)};
g.h.unload=function(){this.player.S("mdxautoplaycanceled");this.w=this.u;g.Le(this.B,this.o);this.o=this.B=null;g.wL.prototype.unload.call(this);g.dT(this.player.app,5);Q8(this)};
g.h.X=function(){g.Wo(this.A);g.wL.prototype.X.call(this)};
g.h.Rl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.nz.apply(this.B,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.I};
g.h.ZE=function(){return this.loaded?this.B.suggestion:null};
g.h.Ey=function(){return this.o?$7(this.o).P:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.R};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.M().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Qc():!a.isAdPlaying()&&this.player.Qc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.w?a.A+T7(a):a.A,isAtLiveHead:1>=(a.w?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.w?a.u+T7(a):a.u,seekableStart:0<a.B?a.B+T7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.vG=function(){this.o&&this.o.RC()};
g.h.kK=function(a){1==a&&(this.U=this.o?$7(this.o):null)};
g.h.yM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.U=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.Ke(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.U)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.QA=function(){this.P=[this.u].concat(vya());var a=y8()||this.u;R8(this,a);this.player.na("onMdxReceiversChange")};
g.h.NN=function(a){!this.L&&g.eH(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.wM=function(){var a=y8();R8(this,a)};
g.h.vM=function(){this.w=y8()};
g.h.VN=function(){this.L=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.UN=function(){this.L=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Oc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.P;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.P.length&&"cast-selector-receiver"==this.P[1].key?(b&&P7(),!0):!1}};
g.h.wG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Pf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.LL.remote=P8;})(_yt_player);
